ALTER TABLE rounds DROP CONSTRAINT IF EXISTS rounds_ck_inactive_users_non_negative;

ALTER TABLE rounds DROP COLUMN IF EXISTS inactive_users;

ALTER TYPE JOB_TYPE RENAME VALUE 'MARK_INACTIVE' TO 'MARK_INACTIVE_DEPRECATED';
