CREATE TABLE IF NOT EXISTS icebreakers (
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    question TEXT NOT NULL,
    usage_count integer DEFAULT 0 NOT NULL,

    created_at timestamp without time zone DEFAULT NOW()::timestamp NOT NULL,
    updated_at timestamp without time zone DEFAULT NOW()::timestamp NOT NULL,

    CONSTRAINT icebreakers_pk_id PRIMARY KEY (id),
    CONSTRAINT icebreakers_unique_question UNIQUE (question)
);

-- Seed the icebreakers table with questions. ON CONFLICT DO NOTHING ensures that this operation is idempotent.
INSERT INTO icebreakers (question) VALUES
('What’s a personal decision you made that ended up changing your life in an unexpected way?'),
('What''s your favorite way to unwind after a long day?'),
('What''s the most memorable trip you''ve ever taken and what made it so special?'),
('What''s the most interesting thing you''ve learned from a podcast recently?'),
('What''s the most interesting or unusual hobby you''ve ever had?'),
('What''s the most beautiful place you''ve ever seen in-person?'),
('What''s the best thing you''ve learned recently outside of work?'),
('What''s the best meal you''ve ever had and what made it so memorable?'),
('What''s something that you''re looking forward to in the coming months?'),
('What''s one tradition from your childhood that you''d like to pass on?'),
('What''s one thing you''ve done in your career that you''re really proud of?'),
('What''s one thing you think aliens would find most confusing about Earth?'),
('What''s one productivity trick or tool you swear by that others might not know about?'),
('What''s one movie that you can watch over and over again?'),
('What''s one book that you think should be made into a movie or Netflix series?'),
('What''s a topic you could give a 15-minute presentation on without any preparation?'),
('What''s a subject you wish you had paid more attention to in school and why?'),
('What''s a subject you know a surprising amount about?'),
('What''s a small, everyday luxury you couldn''t live without?'),
('What''s a skill you''ve picked up from a hobby that has been surprisingly useful in other areas of your life?'),
('What''s a skill you''ve always wanted to learn, and what''s stopping you?'),
('What''s a question you wish people would ask you more often?'),
('What''s a place you''ve never been to but have always wanted to visit, and why?'),
('What''s a piece of technology you wish existed that would solve a small, everyday annoyance?'),
('What''s a piece of career advice you received that has really stuck with you?'),
('What''s a book that changed your perspective on something?'),
('What''s a piece of advice you''ve received that has always stuck with you?'),
('What''s a movie that you think everyone should see at least once and why?'),
('What''s a movie or TV show you believe is criminally underrated?'),
('What''s a moment in history you wish you could have experienced firsthand?'),
('What''s a hobby you''d love to pick up if time and money were no concern?'),
('What''s a hidden talent you have that might surprise people?'),
('What''s a food you disliked as a child but absolutely love now?'),
('What''s a food combination you love that others might find strange?'),
('What''s a fictional product or gadget you wish existed in real life?'),
('What''s a favorite local spot you''d recommend to a visitor from out of town?'),
('What''s a documentary that completely changed your perspective on a topic?'),
('What''s a dish you''ve perfected cooking, or one you''d love to learn how to make?'),
('What''s a creative project you''re currently working on or would like to start?'),
('What was your favorite TV show or movie from childhood and why?'),
('What''s your ideal weekend if you had no responsibilities and unlimited time?'),
('What''s the most interesting thing you''ve read or watched this year?'),
('What imaginary friend would you create today if you had to have one as an adult?'),
('Imagine you’re hosting a dinner party with 3-5 people from the past. Who would be on your guest list?'),
('You''re given the power to make one weird, funny law that everyone has to follow for a day—what is it?'),
('If your laugh could trigger a superpower, what power would it activate and how would you use it?'),
('If you had a time machine, would you go to the future or the past?'),
('If you had to eat one type of cuisine for the rest of your life, what would it be?'),
('If your life were turned into a documentary, what would its title be?'),
('If your inner voice had a celebrity narrator, who would it be and why?'),
('If you were to write a book, what genre would it be and what would be the basic plot?'),
('If you were to start a podcast, what would it be about?'),
('If you could have dinner with your younger self at any age, what age would that be and what would you tell them?'),
('If you were to design a board game, what would be its theme and how would you win?'),
('If you were given a grant to study anything you wanted, what would you choose to research?'),
('If you had unlimited resources to solve one global issue, which would you choose and what would your first step be?'),
('If you had to teach a class on any topic, what would you teach?'),
('If you had to sum up your job using only emojis, which ones would you choose?'),
('If you had to give a TED Talk about something not related to your job, what would your topic be?'),
('If you had to create a time capsule to be opened in 100 years, what three items would you put inside to represent today''s world?'),
('If you had a personal theme song, what would it be and why?'),
('If you could work remotely from anywhere in the world for a month, where would you choose and why?'),
('If you could witness any event in history, what would it be and why?'),
('If you could travel anywhere in the world right now, where would you go and why?'),
('If you could trade places with anyone for a day, who would it be and what would you do?'),
('If you could swap roles with anyone in your company for a day, who would it be and why?'),
('If you could swap lives with someone from a different profession for a week, who would it be and what would you hope to learn?'),
('If you could star in a movie, what genre would it be and what would your character be like?'),
('If you could spend a week in any fictional world, where would you go?'),
('If you could spend a day observing any animal in its natural habitat, which would you choose?'),
('If you could re-live one day of your life without changing a single thing, which day would you choose?'),
('If you were stuck on an island and could only bring 3 books with you, which ones would you chose?'),
('If you could only keep five apps on your phone and had to delete the rest, which ones would you choose and why?'),
('If you could live in any videogame world for a year, which one would you choose and what would you do?'),
('If you could live in any historical period for a year, which one would you choose and what would you do?'),
('If you could listen to only one album for the rest of your life, what would it be?'),
('If you could learn the complete history of one object, what object would you choose?'),
('If you could learn the complete history of one event, which historical event would you choose?'),
('If you could learn any language fluently in an instant, which one would you choose?'),
('If you could know the absolute truth to one mystery (personal, historical, or scientific), what would you choose?'),
('If you could invite any historical figure for dinner, who would you choose and what meal would you cook for them?'),
('If you could instantly swap minds with any person for a day, who would it be and what would you hope to understand?'),
('If you could instantly become an expert in any practical skill, like carpentry or car repair, what would it be?'),
('If you could implement one workplace tradition or ritual, what would it be?'),
('If you could have dinner with any three fictional characters, who would they be?'),
('If you could have any superpower, what would you choose and what would be the first problem you''d solve with it?'),
('If you could have any mythical creature as a pet, what would you choose?'),
('If you could have any job in the world for just one week, what would it be?'),
('If you could have any fictional character as a mentor, who would you choose and why?'),
('If you could have any famous artist, living or dead, paint your portrait, who would it be?'),
('If you could have any animal''s ability, like a cheetah''s speed or an eagle''s sight, which would you choose and why?'),
('If you could have a conversation with your future self 20 years from now, what would you ask?'),
('If you could have a conversation with any inventor from history, who would it be and what would you ask them?'),
('If you could have a billboard with anything on it, what would it say and why?'),
('If you could go on a road trip with any two fictional characters, who would they be and where would you go?'),
('If you could give your younger self one piece of advice, what would it be?'),
('If you could direct a movie with unlimited budget, who would you cast as the main stars?'),
('If you could design a new monument for your city, what would it commemorate?'),
('If you could design a new holiday, what would it celebrate and how would people observe it?'),
('If you could design a commercial to be played at the Superbowl, what would it be about and why?'),
('If you could create a new flavor of ice cream, what would it be and what would you call it?'),
('If you could commission a piece of art from any artist, living or dead, what would you ask them to create?'),
('If you could build your dream house, what''s one unique or unconventional feature it would have?'),
('If you could be an extra in any movie, which one would you choose to be in the background of?'),
('If you could be a contestant on any game show, which one would you choose?'),
('If you could attend a professional conference anywhere in the world, where would you go and what would it be about?'),
('If you could add an extra hour to your day, how would you spend it?'),
('If you could add a new rule to any sport, what would it be and why?'),
('If everyone could receive one universal life lesson at birth, what do you think it should be?')
ON CONFLICT (question) DO NOTHING;
