---
name: go
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'cmd/app-manifest/**'

permissions:
  contents: read

jobs:
  build:
    name: build/container
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build app-manifest container image
        run: make docker/build/chat-roulette
